codecov:

coverage:
  status:
    project:
      default: on
      unittest:
        flags: unittest
        target: 85%
      featuretest:
        flags: featuretest
flags:
  unittest:
    # only test unittests
    paths:
      - Tests/
  featuretest:
    # only test featuretest
    paths:
      - feature-test/

comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
