name: Build

on: [push, pull_request]

jobs:
  build:
    name: SDK build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - run: yarn install && CI=false yarn run build
        working-directory: ./
      - uses: codecov/codecov-action@v2.1.0
        with:
            flags: unittests # optional
            github_checks: true
            files: ./codecov.yml
            name: codecov-umbrella # optional
            fail_ci_if_error: true # optional (default = false)
            verbose: true # optional (default = false)
